all:

install:
	cp -p tmpl_log_tail.pm ../sign_your_name/
	cp -p level_1_log_tail.pl ../sign_your_name/level_1_log_tail.cgi
	cp -p level_2_log_tail.pl ../sign_your_name/level_2_log_tail.cgi
	cp -p level_3_log_tail.pl ../sign_your_name/level_3_log_tail.cgi
	cp -p add_log.pl ../sign_your_name/add_log.cgi
	cp -p view_logs.pl ../view_logs.cgi
	cp -p laundry_logs.pl ../laundry_logs.cgi

uninstall:
	rm -f ../sign_your_name/tmpl_log_tail.pm
	rm -f ../sign_your_name/level_1_log_tail.cgi
	rm -f ../sign_your_name/level_2_log_tail.cgi
	rm -f ../sign_your_name/level_3_log_tail.cgi
	rm -f ../sign_your_name/add_log.cgi
	rm -f ../view_logs.cgi
	rm -f ../laundry_logs.cgi
